spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8888}

wechat:
  appid: wx7277976cd1ab9064
  secret: b854a7ab20934902d5ccf9b6a4aac0f4

db:
  url: jdbc:h2:~/zgf
  username: sa
  password: sa
  driver: org.h2.Driver
